language: clojure
deploy:
  skip_cleanup: true
  provider: script
  script: lein deploy
  on:
    tags: true
notifications:
  slack:
    secure: ilNqO2yGeCnunIlbLxjRpktFPugfNILBGyVKKgk3QFAQW2eWKdIR17RhOfN204nRBNTG+LKbAldOOd4tEPfHmSWzx1R/jLsFpfe56FwrtaYA3xKOJkYFnB+jthZb7HbsuTV2umQ3Z5vGB6rdiySAaXYWExchO2IDxa0T4aJfBCk=
